version: '3.6'

services:
  chatgpt:
    build: .
    ports:
      - 3000:3000
    environment:
      - 'OPENAI_API_KEY='

  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - 8888:8888
